export type QuizExample = {
  text: string;
  isScam: boolean;
};

export const EXAMPLES: QuizExample[] = [
  { text: "Hey, I need your help urgently. Can you send me some money?", isScam: true },
  { text: "We noticed suspicious activity on your account. Please verify your details.", isScam: true },
  { text: "Click here to claim your exclusive prize before it expires!", isScam: true },
  { text: "This is IT support. We need remote access to your computer to fix an issue.", isScam: true },
  { text: "Hi, I'm from the bank. Can you confirm your card number for security?", isScam: true },
  { text: "Your package couldn't be delivered. Pay a small fee to reschedule.", isScam: true },
  { text: "Hello Mom, I lost my wallet. Can you wire me some cash?", isScam: true },
  { text: "We've detected a virus on your device. Call this number for assistance.", isScam: true },
  { text: "Congrats! You have been selected for a $500 shopping voucher.", isScam: true },
  { text: "Your PayPal account is restricted. Log in to restore access.", isScam: true },
  { text: "You owe unpaid taxes. Immediate payment required to avoid legal action.", isScam: true },
  { text: "Can you send me the verification code you just received?", isScam: true },
  { text: "Your Netflix subscription has expired. Update your payment information.", isScam: true },
  { text: "We need to confirm your identity. Please reply with your full name and address.", isScam: true },
  { text: "Hi, this is your friend. I changed my number, can you text me back?", isScam: true },
  { text: "Act now! Your account will be suspended unless you verify your info.", isScam: true },
  { text: "You have a pending refund. Please provide your bank details.", isScam: true },
  { text: "This is the IRS. You must pay immediately to avoid prosecution.", isScam: true },
  { text: "Your computer is infected. Download this software to clean it.", isScam: true },
  { text: "You've won a free cruise! Register your details to claim.", isScam: true },
  { text: "We are updating our privacy policy. No action needed.", isScam: false },
  { text: "Amazon: Your order #12345 has shipped. Track your package here.", isScam: false },
  { text: "Reminder: Dentist appointment tomorrow at 3pm.", isScam: false },
  { text: "Monthly statement now available online.", isScam: false },
  { text: "Welcome to our newsletter! Unsubscribe anytime.", isScam: false },
  { text: "Flight itinerary for next week attached.", isScam: false },
  { text: "Password changed successfully.", isScam: false },
  { text: "Subscription renewal was successful.", isScam: false },
  { text: "Package delivered. Thank you for shopping with us.", isScam: false },
  { text: "Account settings updated.", isScam: false },
  { text: "Thank you for your payment.", isScam: false },
  { text: "Reservation confirmed for Saturday.", isScam: false },
  { text: "Support ticket received. We'll get back to you soon.", isScam: false },
  { text: "Order is being processed.", isScam: false },
  { text: "Feedback appreciated. Have a great day!", isScam: false },
  { text: "Account is secure.", isScam: false },
  { text: "Hi John, your meeting is scheduled for 2pm.", isScam: false },
  { text: "Your subscription has started. Enjoy our service!", isScam: false },
  { text: "Payment received. Invoice attached.", isScam: false },
  { text: "Booking confirmation attached.", isScam: false },
  { text: "Password reset request was successful.", isScam: false },
  { text: "Travel itinerary attached.", isScam: false },
  { text: "Support request is being reviewed.", isScam: false },
  { text: "Order shipped and on its way.", isScam: false },
  { text: "Account is active and secure.", isScam: false },
  { text: "Monthly newsletter is here.", isScam: false },
  { text: "Parcel will arrive between 2-4pm.", isScam: false },
  { text: "Appointment confirmed.", isScam: false },
  { text: "Payment processed successfully.", isScam: false },
  { text: "Account preferences updated.", isScam: false },
  { text: "Invoice attached.", isScam: false },
  { text: "Account will be reviewed soon.", isScam: false },
  { text: "Payment receipt attached.", isScam: false },
  { text: "Delivery scheduled for tomorrow.", isScam: false },
  { text: "Account update was successful.", isScam: false },
  { text: "Account has been verified.", isScam: false },
  { text: "Password change was successful.", isScam: false },
  { text: "Account is now active.", isScam: false },
  { text: "Order confirmation attached.", isScam: false },
  { text: "Account is in good standing.", isScam: false },
  { text: "Your account has been compromised. Click here to reset your password.", isScam: true },
  { text: "Congratulations! You've won a $1,000 gift card. Claim now.", isScam: true },
  { text: "This is your bank. Please verify your login details immediately.", isScam: true },
  { text: "Can you send me the code you just received? I need it for my account.", isScam: true },
  { text: "Your package is waiting for delivery confirmation. Click here.", isScam: true },
  { text: "Hi Mom, I lost my phone. Can you send money to this account?", isScam: true },
  { text: "We noticed unusual activity on your account. Log in to secure it.", isScam: true },
  { text: "Your tax refund is ready. Submit your details to receive it.", isScam: true },
  { text: "You have a new voicemail. Listen now.", isScam: true },
  { text: "Your Netflix subscription has expired. Update payment info.", isScam: true },
  { text: "This is IT support. Please install this software to fix your computer.", isScam: true },
  { text: "Your PayPal account is on hold. Resolve now.", isScam: true },
  { text: "You've been selected for a secret shopper job. Apply here.", isScam: true },
  { text: "Your friend sent you a photo. View it here.", isScam: true },
  { text: "Your mobile service will be disconnected. Update payment info.", isScam: true },
  { text: "Your computer is infected. Call this number for support.", isScam: true },
  { text: "Your child was in an accident. Send money for hospital bills.", isScam: true }
];